<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day02_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [13]:
myindex = ['USA', 'Canada', 'Mexico'] # create a list of countries
mydata = [1776, 1867, 1821] # create a list of data
myser = pd.Series(data = mydata, index = myindex) # join then and make it a series
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [17]:
ages = {'sam':5, 'frank':10, 'spike':7} # create a dict of index and data
ageser = pd.Series(ages) # this converts a dict into a pandas series
ageser

sam       5
frank    10
spike     7
dtype: int64

In [26]:
q1 = {'japan':80, 'china':450, 'india':200, 'usa':250}
q2 = {'brazil':100, 'china':500, 'india':210, 'usa':260}
q1sales = pd.Series(q1)
q2sales = pd.Series(q2)
q1sales.keys() # returns all the keys
q2sales.keys() # returns all the keys
q1sales + q2sales # this gives NaN to those keys which are not in both the dicts
q1sales.add(q2sales, fill_value = 0) # fill_value fills existing missing(NaN) values we used here to give value as zero to keys which are not in the dict

brazil    100.0
china     950.0
india     410.0
japan      80.0
usa       510.0
dtype: float64