<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day02_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
import pandas as pd

In [12]:
from google.colab import files
uploaded = files.upload()

Saving tips.csv to tips (1).csv

In [13]:
# Series

myindex = ['USA', 'Canada', 'Mexico'] # create a list of countries
mydata = [1776, 1867, 1821] # create a list of data
myser = pd.Series(data = mydata, index = myindex) # join then and make it a series
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [14]:
ages = {'sam':5, 'frank':10, 'spike':7} # create a dict of index and data
ageser = pd.Series(ages) # this converts a dict into a pandas series
ageser

sam       5
frank    10
spike     7
dtype: int64

In [15]:
q1 = {'japan':80, 'china':450, 'india':200, 'usa':250}
q2 = {'brazil':100, 'china':500, 'india':210, 'usa':260}
q1sales = pd.Series(q1)
q2sales = pd.Series(q2)
q1sales.keys() # returns all the keys
q2sales.keys() # returns all the keys
q1sales + q2sales # this gives NaN to those keys which are not in both the dicts
q1sales.add(q2sales, fill_value = 0) # fill_value fills existing missing(NaN) values we used here to give value as zero to keys which are not in the dict

brazil    100.0
china     950.0
india     410.0
japan      80.0
usa       510.0
dtype: float64

In [16]:
# DataFrame

np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
mydata
myindex = ['CA','NY','AZ','TX']
mycolumns = ['Jan','Feb','Mar']
df = pd.DataFrame(data = mydata, index = myindex, columns = mycolumns) # this is how a DataFrame is created it has 3 input parameters data, index and columns
df

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [17]:
df = pd.read_csv('tips.csv')
df.columns
df.index
# df.info() # gives the info of the whole DataFrame
df.describe().transpose() # describes all the statistic data of the DataFrame and .transpose() flips the df
df.head() # returns top 5 rows
df['tip_percentage'] = np.round(100 * df['tip'] / df['total_bill']) # adds a new column in the DataFrame and np.round() round's off the number
df.drop('tip_percentage', axis = 1) # .drop() this removes/drops a row or column depends on axis value
df = df.set_index('CC Number') # sets a column to an index
df.reset_index() # resets the df to default but new created things will exist but this doesn't save until i use df = df.reset_index()
df.iloc[0:4] # gives all the information of index at location 0
df.drop(4478071379779230, axis = 0) # this removes the index = 2 of axis = 0

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,tip_percentage
CC Number,,,,,,,,,,
3560325168603410,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,6.0
6011812112971322,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,17.0
4676137647685994,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,14.0
4832732618637221,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,15.0
213140353657882,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,19.0
...,...,...,...,...,...,...,...,...,...,...
5296068606052842,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,20.0
3506806155565404,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,7.0
6011891618747196,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,9.0
4375220550950,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,10.0
3511451626698139,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,16.0

In [18]:
# Conditional filtering
df = pd.read_csv('tips.csv')

df['total_bill'] > 20 # this returns a boolean df
newdf = df[df['total_bill'] > 20] # this returns the new dataframe filtered by the condition
newdf = newdf[newdf['sex'] == 'Male']
newdf = newdf[newdf['size'] >= 3]
newdf = newdf[newdf['smoker'] == 'Yes']
# both does the same work but difference in writing it
newdf_combined = df[(df['total_bill'] > 20) & (df['sex'] == 'Male') & (df['size'] >= 3) & (df['smoker'] == 'Yes')] # combining conditions
newdf_combined = newdf_combined[newdf_combined['day'].isin(['Sun', 'Sat', 'Fri'])] # .isin() is used for many options

In [19]:
def last_four(num):
  return int(str(num)[-4:]) # this is how a function is created in python
df['CC Number'].apply(last_four) # here's how we implement it using .apply()
pd.Series(np.vectorize(last_four)(df['CC Number'])) # np.vectorize(#function)(df[]) this reduces time complexity as compared to .apply()

def bill(num):
  if(num > df['total_bill'].mean()): return '$$'
  else: return '$'
df['total_bill'].apply(bill)
df['yelp'] = pd.Series(np.vectorize(bill)(df['total_bill']))

# converting def function to lambda expression
def double(num):
  return num*2
# in lambda expression
lambda num: num*2

# example
df['total_bill'].apply(double)
df['total_bill'].apply(lambda num: num*2)

# applying custom function on more than 1 column
def quality(total_bill, tip):
  if tip/total_bill > 0.15:
    return "generous"
  else:
    return "other"

# np.vecctorize()() has a easy syntax and is faster
df['quality'] = df[['total_bill','tip']].apply(lambda df: quality(df['total_bill'], df['tip']),axis = 1)
df['quality'] = np.vectorize(quality)(df['total_bill'], df['tip']) # we will be using this way more

In [54]:
df = pd.read_csv('tips.csv')
df.sort_values(['tip', 'size']) # sorts first with tip and then by size
df['total_bill'].idxmax() # returns the index of the max value in the selected column
df['sex'].value_counts() # how to get the count value
df['day'].nunique() # returns the number of unique

df['sex'].replace(['Female', 'Male'], ['F', 'M']) # used to replace
# another way by using .map() method
mymap = {'Female':'F', 'Male':'M'}
df['sex'].map(mymap)

df[df["total_bill"].between(10, 20, inclusive="both")]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3522866365840377
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3532124519049786
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,566287581219
...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4097938155941930
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139