<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day02_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import numpy as np
import pandas as pd

In [78]:
myindex = ['USA', 'Canada', 'Mexico'] # create a list of countries
mydata = [1776, 1867, 1821] # create a list of data
myser = pd.Series(data = mydata, index = myindex) # join then and make it a series
myser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [79]:
ages = {'sam':5, 'frank':10, 'spike':7} # create a dict of index and data
ageser = pd.Series(ages) # this converts a dict into a pandas series
ageser

sam       5
frank    10
spike     7
dtype: int64

In [80]:
q1 = {'japan':80, 'china':450, 'india':200, 'usa':250}
q2 = {'brazil':100, 'china':500, 'india':210, 'usa':260}
q1sales = pd.Series(q1)
q2sales = pd.Series(q2)
q1sales.keys() # returns all the keys
q2sales.keys() # returns all the keys
q1sales + q2sales # this gives NaN to those keys which are not in both the dicts
q1sales.add(q2sales, fill_value = 0) # fill_value fills existing missing(NaN) values we used here to give value as zero to keys which are not in the dict

brazil    100.0
china     950.0
india     410.0
japan      80.0
usa       510.0
dtype: float64

In [124]:
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))
mydata
myindex = ['CA','NY','AZ','TX']
mycolumns = ['Jan', 'Feb', 'Mar']
df = pd.DataFrame(data = mydata, index = myindex, columns = mycolumns) # this is how a DataFrame is created it has 3 input parameters data, index and columns
df

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [170]:
df = pd.read_csv('tips.csv')
df.columns
df.index
# df.info() # gives the info of the whole DataFrame
df.describe().transpose() # describes all the statistic data of the DataFrame and .transpose() flips the df
df.head() # returns top 5 rows
df['tip_percentage'] = np.round(100 * df['tip'] / df['total_bill']) # adds a new column in the DataFrame and np.round() round's off the number
df = df.drop('tip_percentage', axis = 1) # .drop() this removes/drops a row or column depends on axis value
df = df.set_index('CC Number') # sets a column to an index
df.reset_index() # resets the df to default but new created things will exist but this doesn't save until i use df = df.reset_index()
df.iloc[0:4] # gives all the information of index at location 0
df.drop(4478071379779230, axis = 0) # this removes the index = 2 of axis = 0

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name
CC Number,,,,,,,,,
3560325168603410,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham
6011812112971322,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters
4676137647685994,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris
4832732618637221,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter
213140353657882,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith
...,...,...,...,...,...,...,...,...,...
5296068606052842,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila
3506806155565404,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders
6011891618747196,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong
4375220550950,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon
3511451626698139,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin